// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";

// COMPONENTS //
import Head from "next/head";
import Footer from "../../src/components/Footer";
import Header from "../../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import Loader from "@/components/Loader";
// SECTIONS //
// PLUGINS //

// STYLES //
import styles from "../../src/styles/pages/product/AmusementGames.module.scss";

//	IMAGES	//
import banner from "../../public/img/product/amusement-games/banner.jpg";
import productImg from "../../public/img/product/amusement-games/product-img.png";
import arrow from "../../public/img/arrow.svg";
import closeIcn from "../../public/img/close.svg";
import popIMg from "../../public/img/product/amusement-games/pop_img.jpg";
import ytImg from "../../public/img/product/amusement-games/youtubeIcn.svg";

/** Amusement Games Page */
export default function AmusementGames() {
	const [showPopup, setShowPopup] = useState(false);
	/** openPopup function */
	const openPopup = () => {
		setShowPopup(true);
		const bodyTg = document.querySelector("body");
		bodyTg.style.overflow = "hidden";
	};
	/** closePopup function */
	const closePopup = () => {
		setShowPopup(false);
		const bodyTg = document.querySelector("body");
		bodyTg.style.overflow = "unset";
	};
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);

	return (
		<div>
			<Head>
				<title>Amusement Games</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.AmusementGamesPage}`}>
				<InsideBanner
					bannerTitle="Crafting Timeless Joy from <br/> Retro Gems to Futuristic Thrills"
					bannerImg={banner.src}
					mobileImg={banner.src}
				/>

				<section className={`${styles.GamesSection} dot_animation_box ptb_100`}>
					<div className="container">
						<div className={`${styles.games_info_sec} f_w_j`}>
							<div className={`${styles.games_filter_sec} pt_10`}>
								<div className="product_filer_sec">
									<div className="product_names">
										<h5 className="paraTxt_18 text_600 ptb_10">New Release</h5>
									</div>
									<div className="product_names">
										<h5 className="paraTxt_18 text_600 ptb_10">Amusement Games</h5>
										<h6 className="paraTxt_16 color_black_opacity pb_20 active_product">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
									</div>
								</div>
							</div>
							<div className={`${styles.games_product_sec}`}>
								<div className={`${styles.product_info_style}`}>
									<h2 className="heading_text_55 color_white pb_20">Video Games</h2>
									<h4 className="text_24 text_500 color_white pb_40">
										Fast & Furious Action with Our Video Games
									</h4>
									<div className={`${styles.product_info_style}`}>
										<div className="ImgHeadingArrowStyle">
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow" onClick={openPopup}>
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
				{showPopup && (
					<div className={styles.popup_overlay}>
						<div className={styles.popup_content}>
							<div className={styles.popup_content_inner}>
								<div className={styles.popup_header}>
									<button onClick={closePopup}>
										<img src={closeIcn.src} alt="" />
									</button>
								</div>
								<div className={styles.popup_body}>
									<div className={`${styles.popup_flx} row`}>
										<div className={styles.popup_img_item}>
											<img src={popIMg.src} alt="" />
										</div>
										<div className={styles.popup_content_item}>
											<h3 className={`${styles.popHead} text_24`}>ATV Slam Twin Std</h3>
											<p className={`${styles.paraTxt} paraTxt_16`}>
												ATV Slam offers a thrilling ATV racing experience with realistic
												motion and exotic environments. Race through 10 different
												environments, perform stunts and choose from 5 unique characters and
												vehicles in this adrenaline-pumping game.
											</p>
											<p className={`${styles.paraTxt} paraTxt_16`}>
												The cabinet is an attention-grabbing spectacle, featuring a
												life-sized, illuminated quadbike with captivating aesthetics, from
												its enormous lit wheels and chrome engine to its stylish liveries
												and top-to-bottom lighting. It demands players' attention with its
												striking visual presence.
											</p>
											<p className={`${styles.paraTxt} paraTxt_16`}>
												<strong>Dimensions</strong>: W:43”x D:83”x H:86
											</p>
											<div className={styles.btn_sec}>
												<a className={`${styles.watch_btn}`} href="" rel="noreferrer">
													Watch Video
												</a>
												<img src={ytImg.src} className={styles.ytImg} alt="" />
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				)}
			</main>
			<Footer />
		</div>
	);
}
