// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";

// COMPONENTS //
import Head from "next/head";
import Footer from "../../src/components/Footer";
import Header from "../../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import Loader from "@/components/Loader";
// SECTIONS //

// PLUGINS //

// STYLES //
import styles from "../../src/styles/pages/product/AmusementGames.module.scss";

//	IMAGES	//
import banner from "../../public/img/product/amusement-games/banner.jpg";
import productImg from "../../public/img/product/amusement-games/product-img.png";
import arrow from "../../public/img/arrow.svg";

/** Amusement Games Page */
export default function AmusementGames() {
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);

	return (
		<div>
			<Head>
				<title>Amusement Games</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.AmusementGamesPage}`}>
				<InsideBanner
					bannerTitle="Crafting Timeless Joy from <br/> Retro Gems to Futuristic Thrills"
					bannerImg={banner.src}
					mobileImg={banner.src}
				/>

				<section className={`${styles.GamesSection} dot_animation_box ptb_100`}>
					<div className="container">
						<div className={`${styles.games_info_sec} f_w_j`}>
							<div className={`${styles.games_filter_sec} pt_10`}>
								<div className="product_filer_sec">
									<div className="product_names">
										<h5 className="paraTxt_18 text_600 ptb_10">New Release</h5>
									</div>
									<div className="product_names">
										<h5 className="paraTxt_18 text_600 ptb_10">Amusement Games</h5>
										<h6 className="paraTxt_16 color_black_opacity pb_20 active_product">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
										<h6 className="paraTxt_16 color_black_opacity pb_20">
											Video Games <span className="product_count">(16)</span>
										</h6>
									</div>
								</div>
							</div>
							<div className={`${styles.games_product_sec}`}>
								<div className={`${styles.product_info_style}`}>
									<h2 className="heading_text_55 color_white pb_20">Video Games</h2>
									<h4 className="text_24 text_500 color_white pb_40">
										Fast & Furious Action with Our Video Games
									</h4>
									<div className={`${styles.product_info_style}`}>
										<div className="ImgHeadingArrowStyle">
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
											<div className="BlockInsideInfo">
												<div className="ProductImg">
													<img
														src={productImg.src}
														className="border_12"
														alt="product img"
													/>
													<h6 className="NewRelease">New Release</h6>
												</div>
												<div className="text_btn_sec f_r_aj_between">
													<h5 className="paraTxt_18 text_500 color_white">
														ATV Slam Twin Std
													</h5>
													<a href="#" rel="noreferrer">
														<button className="btn_arrow">
															<span className={`${styles.arrow_one} arrow_one`}>
																<img src={arrow.src} />
															</span>
															<span className={`${styles.arrow_two} arrow_two`}>
																<img src={arrow.src} />
															</span>
														</button>
													</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}
