// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";
import { ServerHeaders } from "@/utils/RequestHeaders";

// COMPONENTS //
import Head from "next/head";
import Footer from "../../src/components/Footer";
import Header from "../../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import Loader from "@/components/Loader";
import ImagePara from "@/components/ImagePara";
import {
	laneOilingMachine,
	centerStageFurniture,
	pinsetters,
} from "@/data/data-file-1";

import SyncSlider from "@/components/SyncSlider";
import CardHoverYellow from "@/components/CardHoverYellow";
// SECTIONS //

// PLUGINS //
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// STYLES //
import styles from "../../src/styles/pages/brunswick-bowling.module.scss";

//	IMAGES	//
import banner from "../../public/img/brunswick-bowling/banner.jpg";

/** Go Karting Page */
export default function BrunswickBowling({ laneSliderData }) {
	return (
		<div>
			<Head>
				<title>Brunswick Bowling</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.GoKartingPage}`}>
				<InsideBanner
					bannerTitle="Redefining Amusement with <br/>
                    Bowling Brilliance"
					bannerImg={banner.src}
					mobileImg={banner.src}
				/>

				<section
					className={`${styles.banner_bottom_text_sec} dot_animation_box ptb_100`}
				>
					<div className="container">
						<p className="text_24 color_white_opacity l_h_6 toTop" data-scroll>
							CSML is the exclusive distributor of Brunswick Bowling in India and the
							SAARC region. Over the last 25 years, they have jointly set industry
							standards. Their diverse product range simplifies entertainment center
							setup with customizable bowling alleys.
						</p>
					</div>
				</section>

				<SyncSlider data={laneSliderData} />

				<section className="pt_100 pb_60">
					<div className="container">
						<div className={`${styles.pinsetters}`}>
							{pinsetters.map((item, index) => (
								<CardHoverYellow
									full
									key={index}
									title={item.title}
									desc={item.desc}
									boxImg={item.image.src}
								/>
							))}
						</div>
					</div>
				</section>

				<section className="pt_100 pb_60">
					<div className="container">
						{centerStageFurniture.map((item, index) => (
							<ImagePara
								key={index}
								title={item.title}
								desc={item.desc}
								boxImg={item.image.src}
							/>
						))}
					</div>
				</section>

				<section className="pt_100 pb_60">
					<div className="container">
						<h2 className="heading_text_55 pb_50 toTop" data-scroll>
							Lane Oiling Machine
						</h2>
						{laneOilingMachine.map((item, index) => (
							<ImagePara
								key={index}
								title={item.title}
								desc={item.desc}
								boxImg={item.image.src}
							/>
						))}
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}

// data featch in brunswick-bowling //

export async function getStaticProps() {
	//
	const lanes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/lanes?populate=*`,
		ServerHeaders
	);
	const laneSliderData = await lanes.json();

	return {
		props: {
			laneSliderData,
		},
		revalidate: 10,
	};
}
