// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";

// COMPONENTS //
import Head from "next/head";
import Footer from "../../src/components/Footer";
import Header from "../../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import Loader from "@/components/Loader";
// SECTIONS //

// PLUGINS //

// STYLES //
import styles from "../../src/styles/pages/product/GoKarting.module.scss";

//	IMAGES	//
import banner from "../../public/img/product/go-karting/go-karting-banner.jpg";
import entertainmentCenterImg1 from "../../public/img/product/go-karting/entertainment-center-img1.jpg";
import entertainmentCenterImg2 from "../../public/img/product/go-karting/entertainment-center-img2.jpg";
import entertainmentCenterImg3 from "../../public/img/product/go-karting/entertainment-center-img3.jpg";
import sadikartImg1 from "../../public/img/product/go-karting/sadikart-img1.jpg";
import sadikartImg2 from "../../public/img/product/go-karting/sadikart-img2.jpg";
import timingSoftwareImg1 from "../../public/img/product/go-karting/timing-software-img1.jpg";
import timingSoftwareImg2 from "../../public/img/product/go-karting/timing-software-img2.jpg";

/** Services Page */
export default function GoKarting() {
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);
	return (
		<div>
			<Head>
				<title>Go Karting</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			{/* <Loader /> */}
			<main className={`${styles.GoKartingPage}`}>
				<InsideBanner
					bannerTitle="Get Racing with Go-Karting"
					bannerImg={banner.src}
					mobileImg={banner.src}
				/>

				<section
					className={`${styles.banner_bottom_text_sec} dot_animation_box ptb_100`}
				>
					<div className="container">
						<p className="text_24 color_white_opacity l_h_6">
							Revitalize your entertainment center with versatile go-karting experience
							suitable for pure enjoyment at its finest.
						</p>
					</div>
				</section>

				<section className={`${styles.entertainmentCenter} ptb_100`}>
					<div className="container">
						<div className={`${styles.entertainmentCenterContent} pb_40`}>
							<h2 className="heading_text_55 pb_20">
								Rev Up Your Entertainment Center with Go-Karting
							</h2>
							<p className="paraTxt_18 color_black_opacity l_h_6">
								Rev up your excitement with go-karting—an exhilarating, all-encompassing
								experience that captivates enthusiasts of every age and skill level!
								Strategic investments in meticulously designed tracks, high-quality
								karts and stringent safety measures ensure an unmatched adventure for
								patrons. Go-karting transcends conventional entertainment norms,
								providing a unique blend of adrenaline, competition and pure enjoyment.
							</p>
						</div>

						<div
							className={`${styles.entertainmentCenterImgBox} border_animation white_border_animation`}
						>
							<div className={`${styles.entertainmentCenterImgBoxStyle}`}>
								<img src={entertainmentCenterImg1.src} alt="Entertainment Center Img" />
							</div>
							<div className={`${styles.entertainmentCenterImgBoxStyle}`}>
								<div className={`${styles.entertainmentCenterImgBoxStyleRight}`}>
									<img
										src={entertainmentCenterImg3.src}
										alt="Entertainment Center Img"
									/>
								</div>
								<div className={`${styles.entertainmentCenterImgBoxStyleRight}`}>
									<img
										src={entertainmentCenterImg2.src}
										alt="Entertainment Center Img"
									/>
								</div>
							</div>
						</div>
					</div>
				</section>

				<section
					className={`${styles.sadikartTimingSoftware} dot_animation_box ptb_100`}
				>
					<div className="container">
						<h2 className="heading_text_55 color_white pb_50 text_center">
							SODIKART
						</h2>
						<div className={`${styles.partner_superior_flex} f_j`}>
							<div
								className={`${styles.partner_superior_box} border_animation toTop`}
								data-scroll
							>
								<div className={`${styles.partner_superior_content}`}>
									<img className="border_8" src={sadikartImg1.src} alt="img" />
									<div className={`${styles.desc_box}`}>
										<div className={`${styles.desc_title} f_j`}>
											<h3 className="text_24 color_white text_500 ">Global Dominance</h3>
										</div>
										<p className="paraTxt color_white">
											SODIKART, a global karting powerhouse, is distributed worldwide by
											CSML, leading every aspect of the karting experience.
										</p>
									</div>
								</div>
							</div>
							<div
								className={`${styles.partner_superior_box} border_animation toTop`}
								data-scroll
							>
								<div className={`${styles.partner_superior_content}`}>
									<img className="border_8" src={sadikartImg2.src} alt="img" />
									<div className={`${styles.desc_box}`}>
										<div className={`${styles.desc_title} f_j`}>
											<h3 className="text_24 color_white text_500">
												Innovative Leadership
											</h3>
										</div>
										<p className="paraTxt color_white">
											Renowned for daring strategies and patented innovations, SODIKART
											thrives as a financially robust entity on five continents, securing a
											pivotal position in the karting market.
										</p>
									</div>
								</div>
							</div>
						</div>

						<h2 className="heading_text_55 color_white pt_100 pb_50 text_center">
							Timing Software
						</h2>
						<div className={`${styles.luminaries_flex} toTop`}>
							<div className={`${styles.luminaries_box} border_animation`}>
								<div className="dot_one dots_p"></div>
								<div className="dot_two dots_p"></div>
								<div className="dot_three dots_p"></div>
								<div className={`${styles.luminaries_content}`}>
									<img className="border_8" src={timingSoftwareImg1.src} alt="img" />
									<div className={`${styles.desc_box}`}>
										<div className={`${styles.desc_title}`}>
											<h3 className="text_24 text_600">Innovative Environment</h3>
										</div>
										<p className="paraTxt_18 l_h_4 pt_20">
											Elevate go-karting with advanced timing software, offering precise
											data, real-time results, customizable displays, efficient race
											management, insightful analysis and enhanced customer engagement.
										</p>
									</div>
								</div>
							</div>
							<div className={`${styles.luminaries_box} border_animation`}>
								<div className="dot_one dots_p"></div>
								<div className="dot_two dots_p"></div>
								<div className="dot_three dots_p"></div>
								<div className={`${styles.luminaries_content}`}>
									<img className="border_8" src={timingSoftwareImg2.src} alt="img" />
									<div className={`${styles.desc_box}`}>
										<div className={`${styles.desc_title}`}>
											<h3 className="text_24 text_600">Continuous Growth</h3>
										</div>
										<p className="paraTxt_18 l_h_4 pt_20">
											Seamlessly integrates with various timing hardware systems,
											transmitting lap times, updating profiles and generating
											comprehensive reports for optimized resource utilization.
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}
