// MODULES //

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import CountPioneering from "@/sections/about/CountPioneering";
import OurVision from "@/sections/about/OurVision";
import Luminaries from "@/sections/about/Luminaries";
import ExcellenceEntertainment from "@/sections/about/ExcellenceEntertainment";

// SECTIONS //

// PLUGINS //

// STYLES //
import styles from "../src/styles/pages/About.module.scss";

//	IMAGES	//
import about_banner from "../public/img/about/about_banner.jpg";




/** Home Page */
export default function About() {
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.about_page}`}>
      <InsideBanner
				bannerTitle="Over 2 decades of unlocking
        <br className='hidden-xs'> entertainment in every space"
				bannerImg={about_banner.src}
				mobileImg={about_banner.src}
			/>
			<CountPioneering />
			<OurVision />
			{/* <ExcellenceEntertainment />
			<Luminaries /> */}
			
			</main>
			<Footer />
		</div>
	);
}
