// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import Loader from "@/components/Loader";
// SECTIONS //

// PLUGINS //
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// STYLES //
import styles from "../src/styles/pages/Blogs.module.scss";

//	IMAGES	//
import DesktopBanner from "../public/img/blog/blog-banner.jpg";
import MobileBanner from "../public/img/blog/blog-banner.jpg";
import BlogImg from "../public/img/blog/blog-img.jpg";
import arrow from "../public/img/arrow.svg";

/** Blog Page */
export default function Blog() {
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);
	return (
		<div>
			<Head>
				<title>Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.BlogPage}`}>
				<InsideBanner
					bannerTitle="Stay Plugged In with the Industry Trends"
					bannerImg={DesktopBanner.src}
					mobileImg={MobileBanner.src}
				/>

				<section className="dot_animation_box text_center ptb_100">
					<div className="container">
						<div className="width80">
							<p className="text_24 color_white_opacity l_h_6 toTop" data-scroll>
								Stay in the loop on the latest trends, innovations, and insider
								insights. From cutting-edge setups to revolutionary gameplay, we've got
								you covered. Explore, learn, and roll with us as we redefine the arena
								gaming experience.
							</p>
						</div>
					</div>
				</section>

				<section className={`${styles.blog_main_section} ptb_80`}>
					<div className="container">
						<h2 className="heading_text_55 text_center">Blog & Articles</h2>
						<div className={`${styles.blog_info_sec} f_w_j pt_50`}>
							<div
								className={`${styles.blog_info} commonBorderAnimation whiteCommonBorderAnimation mb_80`}
							>
								<div className={`${styles.blog_info_style}`}>
									<img src={BlogImg.src} alt="Blog Img" className="b_r_8" />
								</div>
								<div className={`${styles.blog_info_style}`}>
									<h6 className="paraTxt_16 color_black_opacity pt_20 text_500">
										27 November 2023
									</h6>
									<h4 className="text_24 text_500 pt_10 pb_30">
										Success Stories: Bowling Centers Thriving with CSML and Brunswick
									</h4>
									<a href="#" rel="noreferrer">
										<button className="btn_arrow">
											<span className={`${styles.arrow_one} arrow_one`}>
												<img src={arrow.src} />
											</span>
											<span className={`${styles.arrow_two} arrow_two`}>
												<img src={arrow.src} />
											</span>
										</button>
									</a>
								</div>
							</div>
							<div
								className={`${styles.blog_info} commonBorderAnimation whiteCommonBorderAnimation mb_80`}
							>
								<div className={`${styles.blog_info_style}`}>
									<img src={BlogImg.src} alt="Blog Img" className="b_r_8" />
								</div>
								<div className={`${styles.blog_info_style}`}>
									<h6 className="paraTxt_16 color_black_opacity pt_20 text_500">
										27 November 2023
									</h6>
									<h4 className="text_24 text_500 pt_10 pb_30">
										Success Stories: Bowling Centers Thriving with CSML and Brunswick
									</h4>
									<a href="#" rel="noreferrer">
										<button className="btn_arrow">
											<span className={`${styles.arrow_one} arrow_one`}>
												<img src={arrow.src} />
											</span>
											<span className={`${styles.arrow_two} arrow_two`}>
												<img src={arrow.src} />
											</span>
										</button>
									</a>
								</div>
							</div>
							<div
								className={`${styles.blog_info} commonBorderAnimation whiteCommonBorderAnimation mb_80`}
							>
								<div className={`${styles.blog_info_style}`}>
									<img src={BlogImg.src} alt="Blog Img" className="b_r_8" />
								</div>
								<div className={`${styles.blog_info_style}`}>
									<h6 className="paraTxt_16 color_black_opacity pt_20 text_500">
										27 November 2023
									</h6>
									<h4 className="text_24 text_500 pt_10 pb_30">
										Success Stories: Bowling Centers Thriving with CSML and Brunswick
									</h4>
									<a href="#" rel="noreferrer">
										<button className="btn_arrow">
											<span className={`${styles.arrow_one} arrow_one`}>
												<img src={arrow.src} />
											</span>
											<span className={`${styles.arrow_two} arrow_two`}>
												<img src={arrow.src} />
											</span>
										</button>
									</a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}
