// MODULES //

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import JoinPioneering from "@/sections/career/JoinPioneering";
import CareerSuccess from "@/sections/career/CareerSuccess";

// SECTIONS //

// PLUGINS //

// STYLES //
import styles from "../src/styles/pages/Career.module.scss";

//	IMAGES	//
import career_banner from "../public/img/career/career_banner.jpg";
import Career_bnner_mobile from "../public/img/career/Career_bnner_mobile.jpg";





/** Home Page */
export default function Career() {
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.career_page}`}>
      <InsideBanner
				bannerTitle="Start Your Adventure with CSML"
				bannerImg={career_banner.src}
				mobileImg={Career_bnner_mobile.src}
			/>
      <JoinPioneering />
			<CareerSuccess />
			
			</main>
			<Footer />
		</div>
	);
}
