// MODULES //
import ScrollOut from "scroll-out";
import { useState, useEffect, useRef } from "react";

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import HomeBanner from "@/sections/home/HomeBanner";
import Crafting from "@/sections/home/Crafting";
import ProductCatalogue from "@/sections/home/ProductCatalogue";
import ProductCatalogue2 from "@/sections/home/ProductCatalogue2";
import ValuedDistributors from "@/sections/home/ValuedDistributors";
import PartnerSuperior from "@/sections/home/PartnerSuperior";
import ExperienceIndustry from "@/sections/home/ExperienceIndustry";
import OurClients from "@/sections/home/OurClients";
import Showcase from "@/sections/home/Showcase";
import EnthralledCustomers from "@/sections/home/EnthralledCustomers";
import Loader from "@/components/Loader";
// UTILS //
import { ServerHeaders } from "@/utils/RequestHeaders";

// SECTIONS //
import ParallaxSlider from "@/sections/home/ParallaxSlider";
import ParallaxSlider2 from "@/sections/home/ParallaxSlider2";
// PLUGINS //

// STYLES //
import styles from "../src/styles/pages/Home.module.scss";

/** Home Page */
export default function Home({
	PartenrsSliderData,
	ClientLogosData,
	ShowcaseSliderData,
	EnthralledSliderData,
	craftingStatsData,
}) {
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);
	// console.log(PartenrsSliderData);
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.index_page}`}>
				<HomeBanner />
				<Crafting craftingData={craftingStatsData.data} />
				{/* <ParallaxSlider2 /> */}
				{/* <ParallaxSlider /> */}
				<ProductCatalogue />
				{/* <ProductCatalogue2 /> */}
				<ValuedDistributors />
				<PartnerSuperior data={PartenrsSliderData.data} />
				<ExperienceIndustry />

				<section className={`${styles.bg_black}`}>
					<OurClients clientsData={ClientLogosData.data} />
					<Showcase showcaseData={ShowcaseSliderData.data} />
					<EnthralledCustomers enthralledData={EnthralledSliderData.data} />
				</section>
			</main>
			<Footer />
		</div>
	);
}

export async function getStaticProps() {
	// partners sliders
	const PartenrsSlideRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/partners-sliders?populate=*`,
		ServerHeaders
	);
	const PartenrsSliderData = await PartenrsSlideRes.json();

	// home client logos
	const ClientLogosRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/home-client-logos?populate=*`,
		ServerHeaders
	);
	const ClientLogosData = await ClientLogosRes.json();

	// home showcase success sliders
	const ShowcaseSliderRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/home-showcase-success-sliders?populate=*`,
		ServerHeaders
	);
	const ShowcaseSliderData = await ShowcaseSliderRes.json();

	// home enthralled sliders
	const EnthralledSliderRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/home-enthralled-sliders?populate=*`,
		ServerHeaders
	);
	const EnthralledSliderData = await EnthralledSliderRes.json();
	// home crafting stats data
	const craftingStatsRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/home-stats-section?populate=*`,
		ServerHeaders
	);
	const craftingStatsData = await craftingStatsRes.json();

	return {
		props: {
			PartenrsSliderData,
			ClientLogosData,
			ShowcaseSliderData,
			EnthralledSliderData,
			craftingStatsData,
		},
		revalidate: 10,
	};
}
