// MODULES //

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import HomeBanner from "@/sections/home/HomeBanner";
import Crafting from "@/sections/home/Crafting";
import ProductCatalogue from "@/sections/home/ProductCatalogue";
import ValuedDistributors from "@/sections/home/ValuedDistributors";
import PartnerSuperior from "@/sections/home/PartnerSuperior";
import ExperienceIndustry from "@/sections/home/ExperienceIndustry";
import OurClients from "@/sections/home/OurClients";
import Showcase from "@/sections/home/Showcase";
import EnthralledCustomers from "@/sections/home/EnthralledCustomers";

// SECTIONS //

// PLUGINS //

// STYLES //
import styles from "../src/styles/pages/Home.module.scss";





/** Home Page */
export default function Home() {
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.index_page}`}>
				<HomeBanner />
				<Crafting />
				<ProductCatalogue />
				<ValuedDistributors />
				<PartnerSuperior />
				<ExperienceIndustry />

				<section className={`${styles.bg_black}`}>
					<OurClients />
					<Showcase />
					<EnthralledCustomers />
				</section>
			</main>
			<Footer />
		</div>
	);
}
