// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import Loader from "@/components/Loader";
import TabBtb from "@/components/TabBtb";
// SECTIONS //

// PLUGINS //
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";

// STYLES //
import "react-tabs/style/react-tabs.css";
import styles from "../src/styles/pages/project.module.scss";

//	IMAGES	//
import services_banner from "../public/img/project/banner.jpg";

/** Services Page */
export default function Project() {
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);

	const TabTitle = [
		{
			title: "aaa",
		},
		{
			title: "bbb",
		},
		{
			title: "ccc",
		},
		{
			title: "ddd",
		},
	];
	console.log(TabTitle[0].title);
	return (
		<div>
			<Head>
				<title>Projects</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.ServicesConsultancyPage}`}>
				<InsideBanner
					bannerTitle="Journey through Our Diverse Projects"
					bannerImg={services_banner.src}
					mobileImg={services_banner.src}
				/>

				<section className="ptb_100 dot_animation_box">
					<div className="container">
						<div className={`${styles.project_section}`}>
							<div className={`${styles.tab_section}`}>
								{TabTitle.map((item, index) => (
									<TabBtb key={index} title={item.title} white />
								))}
							</div>
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}
