// MODULES //
import { useEffect, useRef, useState } from "react";

// COMPONENTS //
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InsideBanner from "@/components/InsideBanner";
import ContactTab from "@/components/ContactTab";
// SECTIONS //

// PLUGINS //
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";

// STYLES //
import "react-tabs/style/react-tabs.css";
import styles from "../src/styles/pages/ServiceConsultancy.module.scss";

//	IMAGES	//
import services_banner from "../public/img/services_consultancy/services_banner.jpg";
import Sec1_img from "../public/img/services_consultancy/consultancy_img.jpg";
import Tabs_img1 from "../public/img/services_consultancy/tab_img1.jpg";
import Tabs_img2 from "../public/img/services_consultancy/tab_img2.jpg";
import Tabs_img3 from "../public/img/services_consultancy/tab_img3.jpg";

/** Services Page */
export default function Services() {
	return (
		<div>
			<Head>
				<title>Services</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.ServicesConsultancyPage}`}>
				<InsideBanner
					bannerTitle="Services Aligned with your FEC Success"
					bannerImg={services_banner.src}
					mobileImg={services_banner.src}
				/>
				<section className={`${styles.service_sec1}`}>
					<div className="container">
						<div className={`${styles.service_flex} ptb_80`}>
							<div className={`${styles.info_bx}`}>
								<div className={`${styles.info_head} heading_text_55 pb_30`}>
									Turnkey Consultancy Solution for Entertainment Center Success
								</div>
								<div className={`${styles.info_para} text_sm text_400`}>
									CSML is the pioneering force behind exceptional Indoor Amusement
									Centers (IAC). We specialize in turning ordinary spaces into
									extraordinary amusement centers. Our consultancy services are designed
									to guide you through every step of the process, from conceptualization
									to execution.As industry pioneers in Indoor Amusement Centers (IAC), we
									offer meticulously tailored end-to-end solutions to streamline the
									complexities of managing multiple providers.
								</div>
							</div>
							<div className={`${styles.img_bx}`}>
								<img className="img" src={Sec1_img.src} />
							</div>
						</div>
					</div>
					{/* <ContactForm /> */}
				</section>
				<section className={`${styles.service_tabsec} pt_80`}>
					<div className="container">
						<div className={`${styles.sec_title} heading_text_55 pb_50`}>
							Comprehensive Services for
							<br /> Your Center Success
						</div>
					</div>
					<Tabs>
						<TabList>
							<Tab>Planning and Layout Design</Tab>
							<Tab>Exclusive Distribution</Tab>
							<Tab>Tailored Amusement Equipment Selection</Tab>
							<Tab>Logistics & Import</Tab>
							<Tab>Installation & Training</Tab>
							<Tab>Pre & Post Operation Support Services</Tab>
						</TabList>
						<div className="container">
							<TabPanel>
								<div className={`${styles.tabs_bx} `}>
									<div className={`${styles.tabs_img}`}>
										<img className="img" src={Tabs_img1.src} />
									</div>
									<div className={`${styles.tabs_info}`}>
										<p className={`${styles.info_title} font_secondary`}>
											Planning and Layout Design
										</p>
										<p className={`${styles.info_desc} text_sm font_secondary`}>
											Our expertise in optimizing available space transforms it into a
											bespoke arcade amusement hub. We provide specialized layout plans
											designed to suit your location, complete with electrical layout
											plans, operating manuals, and ongoing support.
										</p>
									</div>
								</div>
							</TabPanel>
							<TabPanel>
								<div className={`${styles.tabs_bx} `}>
									<div className={`${styles.tabs_img}`}>
										<img className="img" src={Tabs_img2.src} />
									</div>
									<div className={`${styles.tabs_info}`}>
										<p className={`${styles.info_title} font_secondary`}>
											Exclusive Distribution
										</p>
										<p className={`${styles.info_desc} text_sm font_secondary`}>
											What sets us apart is our exclusive distribution of industry-leading
											brands. Our substantial buying power and involvement in multiple
											projects enable us to offer competitive prices without compromising
											on quality. This ensures that you receive top-notch amusement
											equipment that aligns with your budgetary requirements.
										</p>
									</div>
								</div>
							</TabPanel>
							<TabPanel>
								<div className={`${styles.tabs_bx} `}>
									<div className={`${styles.tabs_img}`}>
										<img className="img" src={Tabs_img3.src} />
									</div>
									<div className={`${styles.tabs_info}`}>
										<p className={`${styles.info_title} font_secondary`}>
											Tailored Amusement Equipment Selection
										</p>
										<p className={`${styles.info_desc} text_sm font_secondary`}>
											At CSML, we specialize in curating a diverse mix of entertainment
											equipment tailored to high-thrill and family-friendly experiences. We
											prioritize creating unforgettable experiences by analyzing your
											audience's demographics, age groups, and budget considerations. Our
											goal is to maximize revenue while appealing to your guests' specific
											interests.
										</p>
									</div>
								</div>
							</TabPanel>
						</div>
					</Tabs>
					<ContactTab />
				</section>
			</main>
			<Footer />
		</div>
	);
}
