// MODULES //
import { useEffect, useRef, useState } from "react";
import ScrollOut from "scroll-out";

// COMPONENTS //
import Head from "next/head";
import Footer from "../../src/components/Footer";
import Header from "../../src/components/Header";
import Loader from "@/components/Loader";

// SECTIONS //

// utils //
import { ServerHeaders } from "@/utils/RequestHeaders";

// PLUGINS //
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import parse from "html-react-parser";

// STYLES //
import styles from "../../src/styles/pages/Blogs.module.scss";

//	IMAGES	//
import BlogBanner from "../../public/img/blog/blog-inside-banner.jpg";
import BlogImg from "../../public/img/blog/blog-img.jpg";
import arrow from "../../public/img/arrow.svg";
import facebook from "../../public/img/facebook.svg";
import twitter from "../../public/img/twitter.svg";
import instagram from "../../public/img/instagram.svg";

/** Blog Page */
export default function BlogInside({ BlogData, RelatedBlogData }) {
	useEffect(() => {
		ScrollOut({
			once: true,
		});
	}, []);
	return (
		<div>
			<Head>
				<title>Blog Inside</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Loader />
			<main className={`${styles.BlogInsideSection}`}>
				<section className="coming_from_cms dot_animation_box page_space">
					{/* <div className="container">
						<h1>
							Striking Gold: A Comprehensive Guide to Elevating Your Bowling Center
							with Brunswick Bowling Equipment
						</h1>
						<br />
						<div className="blog_info">
							<h6>27 Nov, 2023</h6>
							<h6>5 Min Read</h6>
							<div className="share_sec">
								<h6>Share</h6>
								<div className="share_icon">
									<a href="">
										<img src={twitter.src} alt="" />
									</a>
									<a href="">
										<img src={facebook.src} alt="" />
									</a>
									<a href="">
										<img src={instagram.src} alt="" />
									</a>
								</div>
							</div>
						</div>
						<br />
						<img src={BlogBanner.src} alt="Blog Inside Img" />
						<br />
						<p>
							In the vibrant world of leisure and entertainment, few activities
							encapsulate the timeless charm and camaraderie that bowling brings to
							enthusiasts. Bowling transcends generational boundaries, acting as a
							conduit that unites people for moments of joy, laughter, and friendly
							competition. For Bowling Center Owners, recognizing the profound impact
							of curating an environment that ensures patron safety while enhancing
							their overall experience is paramount. This recognition transforms the
							selection of bowling equipment from a mere choice into a pivotal
							decision. In the realms of reliability, innovation, and quality, one name
							consistently rises above the rest—Brunswick Bowling.
						</p>
						<br />
						<br />
						<h3>A Legacy of Innovation</h3>
						<br />
						<p>
							The interwoven destinies of Brunswick and Bowling find a parallel in the
							association of CSML with Brunswick Bowling in India & SAARC Region. The
							ascent of Bowling is intricately linked to the ascendancy of Brunswick.
							Since its inception, Brunswick and Bowling have shared a common vision.
							Brunswick has been a trailblazer, introducing game-changing innovations,
							and this legacy manifests in the excellence of its bowling equipment.
						</p>
						<br />
						<p>
							The relentless pursuit of perfection in equipment design has endowed
							Brunswick with ingenuity unparalleled by any other manufacturer.
							Intelligence, functionality, and overall value are the pillars of
							Brunswick's pride, evident in every piece of Bowling Equipment they
							produce.
						</p>
						<br />
						<br />

						<h3>Global Reach, Local Expertise</h3>
						<br />
						<p>
							Brunswick's commitment to global excellence is highlighted by its
							extensive influence. This commitment ensures that the equipment reaching
							your Bowling Center is backed by a legacy of craftsmanship and
							technological prowess.
						</p>
						<br />
						<p>
							CSML's journey with Brunswick Bowling Products USA has evolved
							significantly, culminating in their role as Exclusive Distributors for
							India & SAARC Region. CSML, in collaboration with Brunswick Bowling, has
							been at the forefront of shaping and promoting the Bowling Industry,
							Centers & Alleys in India & SAARC Region.
						</p>
						<br />
						<br />

						<h3>The CSML Advantage</h3>
						<br />
						<p>
							As a Bowling Center Owner, your investment extends beyond the acquisition
							of equipment; it encapsulates an entire experience. CSML, in synergy with
							Brunswick Bowling, offers more than just state-of-the-art bowling
							equipment. It represents an investment in safety, entertainment, and the
							seamless operation that distinguishes your Bowling Center from others.
						</p>
						<br />
						<p>
							Safety takes precedence in any leisure facility, and with Brunswick
							Bowling equipment, you guarantee a secure and enjoyable experience for
							your patrons. From high-quality bowling balls to cutting-edge pinsetters,
							each piece of equipment is meticulously designed for precision and
							durability, adhering to the highest safety standards in the industry.
						</p>
						<br />
						<p>
							Entertainment forms the nucleus of every successful Bowling Center, and
							Brunswick's commitment to innovation ensures an immersive experience for
							your patrons. Whether through the sleek design of the lanes, interactive
							scoring systems, or dynamic lighting options, each element is crafted to
							elevate the entertainment quotient of your center.
						</p>
						<br />
						<br />

						<h3>Invest Wisely, Reap Rewards</h3>
						<br />
						<p>
							Acknowledging the financial considerations as a Bowling Center Owner,
							CSML, in collaboration with Brunswick Bowling, presents not merely
							equipment but a comprehensive solution tailored to your needs. The
							Brunswick Bowling set up cost is an investment in the success and
							longevity of your center.
						</p>
						<br />
						<p>
							Choosing Brunswick Bowling equipment is an investment in the reputation
							of your Bowling Center. It signifies your commitment to providing a
							top-notch bowling experience that entices patrons to return for more.
							When you opt for Brunswick, you're not just acquiring equipment; you're
							investing in the triumph of your business.
						</p>
						<br />
						<br />

						<h3>In Conclusion</h3>
						<br />
						<p>
							The meticulous selection of bowling equipment marks a transformative
							decision for your Bowling Center. Through CSML, exclusive partnership
							with Brunswick Bowling, you're not merely striking gold; you're ensuring
							a golden experience for your patrons. Safety, entertainment, and a
							prudent investment—choose Brunswick Bowling equipment for a winning
							combination that propels your Bowling Center into a league of its own.
							This comprehensive guide empowers Bowling Center Owners with the insights
							needed to make informed decisions, ensuring a legacy of excellence in the
							realm of bowling entertainment.
						</p>
					</div> */}
					<div className="container">
						<h1>{BlogData?.BlogHeading}</h1>
						<br />
						<div className="blog_info">
							<h6>{BlogData?.BlogDate}</h6>
							<h6>5 Min Read</h6>
							<div className="share_sec">
								<h6>Share</h6>
								<div className="share_icon">
									<a href="">
										<img src={twitter.src} alt="" />
									</a>
									<a href="">
										<img src={facebook.src} alt="" />
									</a>
									<a href="">
										<img src={instagram.src} alt="" />
									</a>
								</div>
							</div>
						</div>
						<br />
						<img
							src={`${process.env.NEXT_PUBLIC_STRAPI_DO_BASE_URL}${BlogData?.BlogInsideBanner.data.attributes.url}`}
							alt="Blog Inside Img"
						/>
						<br />
						{parse(BlogData?.BlogContent)}
					</div>
				</section>

				<section className={`${styles.blog_main_section} pt_80 pb_40`}>
					<div className="container">
						<h2 className="heading_text_55 text_center">Others Blog & Articles</h2>
						<div className={`${styles.blog_info_sec} f_w_j pt_50`}>
							{RelatedBlogData?.map((item) => {
								return (
									<div
										className={`${styles.blog_info} commonBorderAnimation whiteCommonBorderAnimation mb_80`}
									>
										<div className={`${styles.blog_info_style}`}>
											<img
												src={`${process.env.NEXT_PUBLIC_STRAPI_DO_BASE_URL}${item.attributes.BlogThumb?.data.attributes.url}`}
												alt="Blog Img"
												className="b_r_8"
											/>
										</div>
										<div className={`${styles.blog_info_style}`}>
											<h6 className="paraTxt_16 color_black_opacity pt_20 text_500">
												{item.attributes.BlogDate}
											</h6>
											<h4 className="text_24 text_500 pt_10 pb_30">
												{item.attributes.BlogHeading}
											</h4>
											<a href={`/blogs/${item.attributes.BlogSlug}`} rel="noreferrer">
												<button className="btn_arrow">
													<span className={`${styles.arrow_one} arrow_one`}>
														<img src={arrow.src} />
													</span>
													<span className={`${styles.arrow_two} arrow_two`}>
														<img src={arrow.src} />
													</span>
												</button>
											</a>
										</div>
									</div>
								);
							})}
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}
export async function getStaticPaths() {
	const BlogRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/Blogs?populate=*`,
		ServerHeaders
	);
	const BlogData = await BlogRes.json();
	return {
		paths: BlogData.data.map((item) => ({
			params: {
				slug: `${item.attributes.BlogSlug}`,
			},
		})),
		fallback: "blocking", // false or "blocking"
	};
}

export async function getStaticProps({ params }) {
	const BlogRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/Blogs?filters[BlogSlug][$eq]=${params.slug}&populate=*`,
		ServerHeaders
	);
	const BlogData = await BlogRes.json();

	const RelatedBlogRes = await fetch(
		`${process.env.STRAPI_DO_BASE_URL}/api/Blogs?filters[BlogSlug][$ne]=${params.slug}&populate=*`,
		ServerHeaders
	);
	const RelatedBlogData = await RelatedBlogRes.json();
	return {
		props: {
			BlogData: BlogData.data[0].attributes,
			RelatedBlogData: RelatedBlogData.data,
		},
	};
}
